### ISSUE TITLE
How to win DR team with Malak by CLS team

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#102]
_## Issue created anonymously for a user ##_
Last time we are facing nore and more DR squad consists of - DR, BF, HK47, Malak, SithST. It is pretty hard to win. 
It is beatable with CLS, Han, Chewe, r2d2, B2.
Below tactic:
BF must die first by any means and in the first turn max in second, othervise you loose.
Move 1 - Han shoots first. He deal damage even if BF has prediction on her, Chewe helps him.
Move 2 - CLS use 3-d spec. Chewe will attack, now you can ignore taunt. Hit BF with second spec., Chewe should help CLS again. In order to do this, Chewe must put Protection on CLS. CLS should be the weakest toon (health as I understand) but pretty much powerful.
At this point BF normally dies. If not see below.
Move 3 - after attacks of your opponent, turn will return  to CLS. Untill this try hit BF. If Malak rise taunt dont attack him maximum B2 second spec in order to dispell taunt or attack Sith ST with taunt.
(This usually can happens if BF has health around and more then 40 000 points)
Move 4 - kill Sith ST. Not to much worry about.
Move 5 - kill HK47. The sooner the better, cause his spec attack hots pretty powerful.
Move 6 - Kill DR.
Usually at this point Malak is already dead automatically. 
Let me explain.
Do not attack him. At some point he will rise taunt and DR use AOE attack, after this CLS + Han + Chewe will attack him. Malak didnt hit back from this attack. After this finish him because he will have not so much health left. Sometimes you can loose CLS or another toon because of counter attack Malak with draining health, during trying to finish him. Dont worry you will kill him or again DR use AOE attack and you will finish him.
Sometimes you can face situation when DR have small health. Usually it could happenes at point when BF and Sith ST already dead. In this case finish DR, after him HK47. At this point Malak is weaked and can be killed more easy.

**Comment by CoyoteRoadruner** [comment]
Hints and rules.
1. Do not attack Malak till end of battle, normally he dies almost automatically.
2. Speed does matter. Your toons should be as fast as possible. CLS preferably 300 or above, because by turn order ge should move second after Han in order to kill BF. Normally DR, BF have speed roundabout 267-280.
CLS MUST outspeed them. Othervise you loose. Han as faster as possible but not decreasing firepower.
3. Power does matter - your toons should be as powerfull in attack and health/protection as possible.
4. Mods does matter. Toons should be modded in proper way. For Chewe speed not so critical because of helping to CLS and Han, but pretty fast. The more powerfull the better.
5. Relics is are highly reccomended. At least R3 preferably R4 and higher.
6. Examine your enemy - Speed and health of BF and speed of DR. If your CLS slower - even dont try. If BF has 40 000 + health be prepared do not to kill her in first two moves.

With all this you should be able to kill any DR team without R. And almost all teams with R3-4on one or two toons. If Malak R-geared 3+, I wouldnt try. Just look on another toons, if BF will be weak or DR you can try.
Overall BF is a key to win, If you kill her in first two moves you will win.

**Comment by CoyoteRoadruner** [comment]
Of course you need a practise several time.
B2 can be usefull in GG squad, but if you dont have fully ready squad, you can use it here.
I hope this info will be useful.

Version - kill order
DR, BF, HK47, Malak, Thrawn - BF, Thrawn, HK47, DR, Malak
DR, BF,HK47,Malak,Sion(DN) - BF, (DN if present), HK47, DR, Sion, Malak
DR, BF, HK47, Malak, whatever - BF, HK47, whatever, DR, Malak
DR, BF, HK47, Malak, Traya - BF, Traya, HK47, DR, Malak

**Comment by CoyoteRoadruner** [comment]
![Coyote_Roadruner_-_Commander_Luke_Skywalker](https://user-images.githubusercontent.com/58366713/71241249-d69a2b00-2313-11ea-87e0-c6e9d43c65e3.png)

**Comment by CoyoteRoadruner** [comment]
![Screenshot_20191128-221724_Chrome](https://user-images.githubusercontent.com/58366713/71241265-e31e8380-2313-11ea-9705-255d8af3743c.jpg)

**Comment by CoyoteRoadruner** [comment]
![Coyote_Roadruner_-_Han_Solo](https://user-images.githubusercontent.com/58366713/71241345-106b3180-2314-11ea-8b72-549ed8e6b4cb.png)

**Comment by CoyoteRoadruner** [comment]
![Screenshot_20191128-221801_Chrome](https://user-images.githubusercontent.com/58366713/71241368-1b25c680-2314-11ea-9638-f807e938e753.jpg)

**Comment by CoyoteRoadruner** [comment]
![Coyote_Roadruner_-_Chewbacca](https://user-images.githubusercontent.com/58366713/71241427-3db7df80-2314-11ea-8195-cf351fa61ffc.png)

**Comment by CoyoteRoadruner** [comment]
![Screenshot_20191128-221818_Chrome](https://user-images.githubusercontent.com/58366713/71241442-490b0b00-2314-11ea-8e7d-261f5c034c52.jpg)

**Comment by CoyoteRoadruner** [comment]
![Coyote_Roadruner_-_B2_Super_Battle_Droid](https://user-images.githubusercontent.com/58366713/71241485-650eac80-2314-11ea-9ce2-421456ef6f7c.png)

**Comment by CoyoteRoadruner** [comment]
![Screenshot_20191128-221911_Chrome](https://user-images.githubusercontent.com/58366713/71241504-72c43200-2314-11ea-9fb8-344f013879d4.jpg)

**Comment by CoyoteRoadruner** [comment]
![Coyote_Roadruner_-_R2-D2](https://user-images.githubusercontent.com/58366713/71241530-82dc1180-2314-11ea-9845-7a999b1acdeb.png)

**Comment by CoyoteRoadruner** [comment]
![Screenshot_20191128-221844_Chrome](https://user-images.githubusercontent.com/58366713/71241544-8d96a680-2314-11ea-9478-c8c115251747.jpg)

**Comment by bobbybaxter** [comment]
This is a lot to unpack.  I will get to it once my focus moves away from 3v3 counters.

**Comment by CoyoteRoadruner** [comment]
Additional info.
When Malak left only survive from squad he is stunnable by R2D2 usual attack and it helps.
It seems DR prevent Malak from stunning.

**Comment by bobbybaxter** [comment]
Since B2 is such a crucial toon in a GG team, I can't justify adding an entirely new team to the list.  However, I did update the counter strategy to suggest the use of B2.  thanks!
