### ISSUE TITLE
Geonosians ineffective against First Order

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#130]
_## Issue created anonymously for a user ##_
The zeta on Kylo Ren Unmasked's leadership ability, "Merciless Pursuit" creates a situation where First Order gains 5% health and protection every time a status effect is added. Because Geonosians are constantly debuffing, it often results in a Time Out result.

**Comment by Ze-Forgotten** [comment]
Geonosians can be considered a soft counter if you can time genosian spy's special ability (Silent Strike) properly. You need to stack just enough debuffs on the FO team so that Genosian Spy can quickly eliminate them. 

Note: The Hive Mind buff greatly increases Genosian spy's turn meter.

Geonosian Spy gains Stealth for 3 turns at the start of each encounter and whenever he scores a critical hit. During their turn, whenever a Geonosian ally inflicts a debuff on an enemy, Geonosian Spy gains 35% Turn Meter.

Time it right and you can quickly eliminate the most important troops. Mainly want to stop FO excetuioner, First Order trooper or FIrst order officer because those deal big dmg and/or give immense turn meter. Afterwards, go for Kylo ren first to stop the turn meter train for Kylo ren unmasked to constantly taunt and stun.

**Comment by bobbybaxter** [comment]
@Ze-Forgotten, nice work!  I've dropped it from a hard counter to soft and added a counter strategy.  Thanks!
